!My first program
! Program to convert off files (3d meshes generated by tetgen) into vtk files
! (used to visual these meshes in paraview)
! Currently converting protein 1ajj

program off2vtk

integer :: i,j
integer :: num_node
integer :: num_tria
integer :: zero
real*8, allocatable,dimension(:) :: x_pos
real*8, allocatable,dimension(:) :: y_pos
real*8, allocatable,dimension(:) :: z_pos
integer, allocatable,dimension(:,:) :: tria
character :: OFF*10
character :: protein*10
protein = '1ajj'

open (unit = 1, file = TRIM(protein)//".OFF")
do i = 1, 6
read (1,*) 
end do
read (1,*) OFF
read (1,*) num_node, num_tria, zero

allocate(x_pos(num_node))
allocate(y_pos(num_node))
allocate(z_pos(num_node))
allocate(tria(num_tria,4))

do i = 1, num_node
  read(1,*) x_pos(i), y_pos(i), z_pos(i)
end do

do i = 1, num_tria
  read(1,*) tria(i,1), tria(i,2), tria(i,3), tria(i,4) 
end do

close(1)

open (unit = 10, file = TRIM(protein)//".vtk", action = "write", status = "replace")
write(10,'(a)') "# vtk DataFile Version 2.0"
write(10,'(a)') "# you need to write something here, I do not know why"
write(10,'(a)') "ASCII"
write(10,'(a)') ""
write(10,'(a)') "DATASET UNSTRUCTURED_GRID"
write(10,"(A8, I7, A8)"), "POINTS ", num_node, " float"
do i = 1, num_node
  write(10,*) x_pos(i), y_pos(i), z_pos(i)
end do

write(10,"('CELLS ', I7, I8)"), num_tria, num_tria*4
do i = 1, num_tria
  write(10,"(I7, I7, I7, I7)"), tria(i,1), tria(i,2), tria(i,3), tria(i,4)
end do

write(10,"('CELL_TYPES ', I7)"), num_tria
do i = 1, num_tria
   write(10,"(I7)"), 5
end do

write(10,"('POINT_DATA ', I7)"), num_node
write(10,'(a)') "SCALARS conc float"
write(10,'(a)') "LOOKUP_TABLE default"
do i = 1, num_node
   write(10,"(I7)"), 0
end do

end program  off2vtk
